"""
config.py — Pakistan Electronics Intelligence Configuration
─────────────────────────────────────────────────────────────
All 30+ Pakistani electronics stores, coordinates, fuel constants,
and branch data for distance/route optimization.
"""

# ── API Keys ──────────────────────────────────────────────────────────────────
GOOGLE_MAPS_API_KEY = "YOUR_GOOGLE_MAPS_API_KEY_HERE"

# ── Fuel / Travel Constants (Pakistan 2024-25) ────────────────────────────────
FUEL_PRICE_PER_LITER = 300.0      # PKR per liter (petrol)
FUEL_EFFICIENCY_KM_PER_L = 12.0   # Average car ~12 km/liter
FUEL_COST_PER_KM = FUEL_PRICE_PER_LITER / FUEL_EFFICIENCY_KM_PER_L   # ~25 PKR/km
TIME_VALUE_PER_HOUR = 500.0       # Opportunity cost PKR/hour
AVG_SPEED_KMH = 30.0             # Average city driving speed in Pakistan

# ── Scraper Settings ──────────────────────────────────────────────────────────
REQUEST_TIMEOUT = 15
REQUEST_DELAY = 1.5

# ── Category Meta (electronics only) ──────────────────────────────────────────
CATEGORY_META = {
    "electronics": {
        "label": "Electronics",
        "icon": "⚡",
        "description": "All electronics from 30+ Pakistani stores",
    },
}

# ── Store Registry ────────────────────────────────────────────────────────────
# type: "physical" = has a walk-in location, "online" = online-only
# Physical stores have lat/lon for distance calculations

STORES = [
    # ─── Physical Shops (Major Physical & Online Stores) ──────────────────
    {
        "id": "afzal_electronics",
        "name": "Afzal Electronics",
        "url": "https://afzalelectronics.com",
        "type": "physical",
        "city": "Karachi",
        "address": "Electronics Market, Saddar, Karachi",
        "lat": 24.8562,
        "lon": 67.0237,
        "phone": "+92-21-32725555",
    },
    {
        "id": "arduino_pakistan",
        "name": "Arduino Pakistan",
        "url": "https://www.arduinopakistan.com/",
        "type": "physical",
        "city": "Lahore",
        "address": "Hall Road Electronics Market, Lahore",
        "lat": 31.5575,
        "lon": 74.3350,
        "phone": "+92-42-37654321",
    },
    {
        "id": "axis_electronics",
        "name": "Axis Electronics",
        "url": None,
        "type": "physical",
        "city": "Lahore",
        "address": "Hall Road, Lahore",
        "lat": 31.5580,
        "lon": 74.3345,
        "phone": None,
    },
    {
        "id": "chaudhry_electronics",
        "name": "Chaudhry Electronics",
        "url": None,
        "type": "physical",
        "city": "Rawalpindi",
        "address": "Raja Bazaar, Rawalpindi",
        "lat": 33.5972,
        "lon": 73.0479,
        "phone": None,
    },
    {
        "id": "city_electronics",
        "name": "City ElectronicsPk",
        "url": "https://cityelectronics.pk/",
        "type": "physical",
        "city": "Karachi",
        "address": "Tariq Road, Karachi",
        "lat": 24.8704,
        "lon": 67.0631,
        "phone": "+92-21-34556677",
    },
    {
        "id": "college_road",
        "name": "College Road Electronics",
        "url": "https://colgroad.com",
        "type": "physical",
        "city": "Rawalpindi",
        "address": "College Road, Rawalpindi",
        "lat": 33.5961,
        "lon": 73.0518,
        "phone": None,
    },
    {
        "id": "eph",
        "name": "Electronic Power House",
        "url": "https://eph.com.pk",
        "type": "physical",
        "city": "Lahore",
        "address": "Main Boulevard, Lahore",
        "lat": 31.5204,
        "lon": 74.3587,
        "phone": "+92-42-35761234",
    },
    {
        "id": "epro",
        "name": "Electronics Pro",
        "url": "https://www.epro.pk/",
        "type": "physical",
        "city": "Islamabad",
        "address": "Blue Area, Islamabad",
        "lat": 33.7100,
        "lon": 73.0551,
        "phone": None,
    },
    {
        "id": "electronation",
        "name": "Electronation Pakistan",
        "url": "http://www.electronation.pk/",
        "type": "physical",
        "city": "Lahore",
        "address": "Gulberg III, Lahore",
        "lat": 31.5170,
        "lon": 74.3470,
        "phone": None,
    },
    {
        "id": "electrobes",
        "name": "Electrobes",
        "url": "https://electrobes.com",
        "type": "physical",
        "city": "Lahore",
        "address": "Model Town, Lahore",
        "lat": 31.4840,
        "lon": 74.3260,
        "phone": None,
    },
    {
        "id": "evs_electro",
        "name": "EVE-eVision Electronics",
        "url": "https://www.evselectro.com/",
        "type": "physical",
        "city": "Karachi",
        "address": "North Nazimabad, Karachi",
        "lat": 24.9245,
        "lon": 67.0338,
        "phone": None,
    },
    {
        "id": "friends_corp",
        "name": "Friends Corporation",
        "url": "https://friendscorporation.co/",
        "type": "physical",
        "city": "Lahore",
        "address": "Hall Road, Lahore",
        "lat": 31.5578,
        "lon": 74.3342,
        "phone": "+92-42-37231234",
    },
    {
        "id": "galaxy_pk",
        "name": "Galaxy.pk",
        "url": "https://www.galaxy.pk",
        "type": "physical",
        "city": "Karachi",
        "address": "Gulshan-e-Iqbal, Karachi",
        "lat": 24.9215,
        "lon": 67.0935,
        "phone": "+92-21-34821234",
    },
    {
        "id": "hanif_centre",
        "name": "Hanif Centre Electronics",
        "url": "https://hcsupermart.com/",
        "type": "physical",
        "city": "Lahore",
        "address": "Hafeez Centre, Gulberg, Lahore",
        "lat": 31.5175,
        "lon": 74.3505,
        "phone": "+92-42-35761000",
    },
    {
        "id": "homeshopping",
        "name": "Homeshopping.pk",
        "url": "https://www.homeshopping.pk",
        "type": "physical",
        "city": "Karachi",
        "address": "PECHS, Karachi",
        "lat": 24.8659,
        "lon": 67.0651,
        "phone": "0800-SHOPPING",
    },
    {
        "id": "imran_electronics",
        "name": "Imran Electronics",
        "url": "https://imraneshop.com",
        "type": "physical",
        "city": "Lahore",
        "address": "Hall Road Electronics Market, Lahore",
        "lat": 31.5572,
        "lon": 74.3348,
        "phone": None,
    },
    {
        "id": "matrix_electronics",
        "name": "MATRIX Electronics & Communication",
        "url": "http://matrixonline.pk/",
        "type": "physical",
        "city": "Islamabad",
        "address": "Jinnah Super Market, Islamabad",
        "lat": 33.7125,
        "lon": 73.0723,
        "phone": None,
    },
    {
        "id": "mega_pk",
        "name": "Mega.pk",
        "url": "https://www.mega.pk",
        "type": "physical",
        "city": "Karachi",
        "address": "Saddar, Karachi",
        "lat": 24.8565,
        "lon": 67.0230,
        "phone": "+92-21-111-634-263",
    },
    {
        "id": "multan_electronics",
        "name": "Multan Electronics",
        "url": None,
        "type": "physical",
        "city": "Multan",
        "address": "Hussain Agahi, Multan",
        "lat": 30.1984,
        "lon": 71.4734,
        "phone": None,
    },
    {
        "id": "pak_elec_and_electronics",
        "name": "Pakistan Electrical & Electronics",
        "url": None,
        "type": "physical",
        "city": "Karachi",
        "address": "Saddar Electronics Market, Karachi",
        "lat": 24.8555,
        "lon": 67.0235,
        "phone": None,
    },
    {
        "id": "pakistan_electronics",
        "name": "Pakistan Electronics",
        "url": "http://www.pakistanelectronics.com/",
        "type": "physical",
        "city": "Karachi",
        "address": "Gurumandir, Karachi",
        "lat": 24.8700,
        "lon": 67.0315,
        "phone": None,
    },
    {
        "id": "shophive",
        "name": "Shophive.com",
        "url": "https://www.shophive.com",
        "type": "physical",
        "city": "Lahore",
        "address": "Cavalry Ground, Lahore",
        "lat": 31.5125,
        "lon": 74.3595,
        "phone": "0800-746-7484",
    },
    {
        "id": "telemart",
        "name": "Telemart.pk",
        "url": "https://www.telemart.pk",
        "type": "physical",
        "city": "Lahore",
        "address": "Garden Town, Lahore",
        "lat": 31.5152,
        "lon": 74.3345,
        "phone": "042-111-835-362",
    },
    {
        "id": "component_centre",
        "name": "The Component Centre",
        "url": "https://www.thecomponentcentre.com/",
        "type": "physical",
        "city": "Islamabad",
        "address": "I-8 Markaz, Islamabad",
        "lat": 33.6800,
        "lon": 73.0650,
        "phone": None,
    },
    {
        "id": "umar_electronics",
        "name": "Umarelectronics.pk",
        "url": "https://umarelectronics.pk/",
        "type": "physical",
        "city": "Karachi",
        "address": "Bahadurabad, Karachi",
        "lat": 24.8740,
        "lon": 67.0575,
        "phone": None,
    },
    {
        "id": "vmart",
        "name": "VMart.pk",
        "url": "https://www.vmart.pk",
        "type": "physical",
        "city": "Islamabad",
        "address": "F-10 Markaz, Islamabad",
        "lat": 33.6950,
        "lon": 73.0170,
        "phone": None,
    },

    # ─── Online-Only Electronics Stores ───────────────────────────────────
    {
        "id": "art_of_circuits",
        "name": "Art of Circuits",
        "url": "https://artofcircuits.com/shop",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "chip_pk",
        "name": "Chip.pk",
        "url": "https://chip.pk/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "circuit_pk",
        "name": "Circuit.pk",
        "url": "https://circuitpk.enic.pk/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "daraz",
        "name": "Daraz.pk",
        "url": "https://www.daraz.pk",
        "type": "online",
        "city": "Online",
        "address": "Pakistan's #1 Online Marketplace",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": "042-111-132-729",
    },
    {
        "id": "dcart",
        "name": "Dcart.pk",
        "url": "https://dcart.pk/shop/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "digilog",
        "name": "Digilog.pk",
        "url": "https://digilog.pk/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "epal",
        "name": "ePal.pk",
        "url": "https://www.epal.pk/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "ishopping",
        "name": "iShopping.pk",
        "url": "https://www.ishopping.pk",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "mreeco",
        "name": "Mreeco.com",
        "url": "https://www.mreeco.com/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
    {
        "id": "rawlix",
        "name": "Rawlix.com",
        "url": "https://www.rawlix.com/",
        "type": "online",
        "city": "Online",
        "address": "Online Store — Pakistan-wide delivery",
        "lat": 30.3753,
        "lon": 69.3451,
        "phone": None,
    },
]

# ── Build BRANCHES list for distance service (physical stores only) ───────────
# The existing prediction_service.py and decision_service.py expect this format
BRANCHES = []
for store in STORES:
    BRANCHES.append({
        "id": store["id"],
        "name": store["name"],
        "city": store["city"],
        "address": store["address"],
        "lat": store["lat"],
        "lon": store["lon"],
        "phone": store.get("phone", ""),
        "type": store["type"],
        "url": store.get("url", ""),
        "categories": ["electronics"],   # all stores carry electronics
    })

# Helper lookups
STORE_BY_ID = {s["id"]: s for s in STORES}
PHYSICAL_STORES = [s for s in STORES if s["type"] == "physical"]
ONLINE_STORES = [s for s in STORES if s["type"] == "online"]
